{{- $admin := .Values -}}
{{- $cp := .Values.cp -}}
{{- $zoo := .Values.zookeeper -}}
{{- $nacos := .Values.nacos -}}
{{- $prom := .Values.kubePrometheus }}
{{- if eq $admin.deployType "StatefulSet" }}
apiVersion: {{ template "apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ template "admin.name" . }}
  namespace: {{ template "admin.namespace" . }}
  labels:
  {{- include "admin.labels" . | nindent 4 }}
  {{- with $admin.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $admin.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $admin.replicas }}
  {{- if $admin.revisionHistoryLimit }}
  revisionHistoryLimit: {{ $admin.revisionHistoryLimit }}
  {{- end }}
  {{- if $admin.minReadySeconds }}
  minReadySeconds: {{ $admin.minReadySeconds }}
  {{- end }}
  updateStrategy:
  {{- if $admin.updateStrategy }}
  {{- toYaml $admin.updateStrategy | nindent 4 }}
  {{- end }}
  serviceName: {{ template "admin.name" . }}
  selector:
    matchLabels:
    {{- include "admin.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "admin.labels" . | nindent 8 }}
    spec:
      {{- if $admin.imagePullSecrets }}
      imagePullSecrets: {{ toYaml $admin.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if $admin.nodeSelector }}
      nodeSelector: {{ toYaml $admin.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $admin.tolerations }}
      tolerations: {{ toYaml $admin.tolerations | nindent 8 }}
      {{- end }}
      {{- if $admin.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $admin.terminationGracePeriodSeconds }}
      {{- end }}
      serviceAccountName: {{ template "admin.name" . }}
      containers:
      - name: admin
        image: {{ $admin.image.registry }}:{{ $admin.image.tag }}
        imagePullPolicy: {{ $admin.image.pullPolicy }}
        lifecycle:
        {{- if $admin.lifecycleHooks }}
        {{- toYaml $admin.lifecycleHooks | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          {{- if $admin.service.protocol }}
          protocol: {{ $admin.service.protocol }}
          {{- end }}
          containerPort: {{ template "admin.containerPort" . }}
        env:
        {{- $zooName := include "zoo.name" . -}}
        {{- $nacosName := include "nacos.name" . -}}
        {{- $zooReplicas := int $zoo.replicas -}}
        {{- $nacosReplicas := int $nacos.replicas -}}
        {{- $zooHeadless := printf "%s-%s" $zooName "headless" | trunc 63 -}}
        {{- $nacosHeadless := printf "%s-%s" $nacosName "headless" | trunc 63 -}}
        {{- $zooNamespace := include "zoo.namespace" . -}}
        {{- $nacosNamespace := include "nacos.namespace" . -}}
        {{- $clusterDomain := $admin.clusterDomain -}}
        {{- $zooPort := include "zoo.client" . -}}
        {{- $nacosPort := $nacos.serverPort -}}
        {{- if $zoo.enabled }}
        - name: ADMIN_REGISTRY_ADDRESS
          value: zookeeper://{{ range $k, $v := until $zooReplicas }}{{ $zooName }}-{{ $v }}.{{ $zooName }}.{{ $zooNamespace }}.svc.{{ $clusterDomain }}:{{ $zooPort }} {{ end }}
        {{- else if $nacos.enabled }}
        - name: ADMIN_REGISTRY_ADDRESS
          value: nacos://{{ range $k, $v := until $nacosReplicas }}{{ $nacosName }}-{{ $v }}.{{ $nacosName }}.{{ $nacosNamespace }}.svc.{{ $clusterDomain }}:{{ $nacosPort }} {{ end }}
        {{- else }}
        - name: ADMIN_REGISTRY_ADDRESS
          value: zookeeper://{{ range $k, $v := until $zooReplicas }}{{ $zooName }}-{{ $v }}.{{ $zooName }}.{{ $zooNamespace }}.svc.{{ $clusterDomain }}:{{ $zooPort }} {{ end }}
        {{- end }}
        {{- $promName := include "prom.name" . }}
        {{- $promPort := include "prom.port" . }}
        {{- $promStationaryName := printf "-kube-prome-prometheus" }}
        {{- if $prom.enabled }}
        - name: ADMIN_PROMETHEUS_ADDRESS
          value: {{ $promName$promStationaryName }}:{{ $promPort }}
        {{- $grafanaPort := include "grafana.port" . }}
        {{- $grafanaStationaryName := printf "-grafana" }}
        - name: ADMIN_GRAFANA_ADDRESS
          value: {{ $promName$grafanaStationaryName }}:{{ $grafanaPort }}
        {{- end }}
        volumeMounts:
        {{- if $admin.volumeMounts }}
        {{- toYaml $admin.volumeMounts | nindent 8 }}
        {{- end }}
        securityContext:
        {{- if $admin.securityContext }}
        {{- toYaml $admin.securityContext | nindent 10 }}
        {{- end }}
        startupProbe:
        {{- if $admin.startupProbe }}
        {{- toYaml $admin.startupProbe | nindent 10 }}
        {{- end }}
        livenessProbe:
        {{- if $admin.livenessProbe }}
        {{- toYaml $admin.livenessProbe | nindent 10 }}
        {{- end }}
        readinessProbe:
        {{- if $admin.readinessProbe }}
        {{- toYaml $admin.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
        {{- if $admin.resources }}
        {{- toYaml $admin.resources | nindent 10 }}
        {{- end }}
      volumes:
      {{- if $admin.volumes }}
      {{- toYaml $admin.volumes | nindent 6 }}
      {{- end }}
      - name: {{ include "admin.name" . }}-server-config
        configMap:
          name: {{ include "admin.name" . }}-server-config
      - name: scripts
        configMap:
          name: {{ template "job.name" . }}-scripts
      {{- if $cp.tls.secretName }}
      - name: general-tls-cert
        secret:
          secretName: {{ $cp.tls.secretName }}
      {{- else }}
      - name: general-tls-cert
        secret:
          secretName: {{ include "admin.name" . }}-tls-cert
      {{- end }}
      {{- if $cp.tls.caSecretName }}
      - name: general-tls-cert-ca
        secret:
          secretName: {{ $cp.tls.caSecretName }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      {{- with $admin.persistence }}
      storageClassName: {{ .claimName }}
      accessModes:
      - {{ .accessModes }}
      resources:
        requests:
          storage: {{ .size }}
      {{- end -}}
{{- end -}}
