apiVersion: v1
kind: ConfigMap
metadata:
  name: dubbo
  namespace: dubbo-system
  labels:
    app: dubbod
    dubbo.apache.org/rev: default
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: dubbod.dubbo-system.svc:15012
    rootNamespace: dubbo-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'