---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbod
  namespace: dubbo-system
  labels:
    app: dubbod
    dubbo.apache.org/rev: default
spec:
  selector:
    matchLabels:
      app: dubbod
  template:
    metadata:
      labels:
        app: dubbod
    spec:
      serviceAccountName: dubbod
      containers:
        - name: discovery
          image: "mfordjody/planet:0.3.2-debug"
          imagePullPolicy: Always
          args:
            - "discovery"
            - --domain
            - cluster.local
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http-debug
            - containerPort: 15010
              protocol: TCP
              name: grpc-xds
            - containerPort: 15012
              protocol: TCP
              name: tls-xds
            - containerPort: 15017
              protocol: TCP
              name: https-webhooks
          env:
            - name: REVISION
              value: default
            - name: DUBBO_CERT_PROVIDER
              value: dubbod
            - name: CLUSTER_ID
              value: "Kubernetes"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
          resources:
            requests:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
          - mountPath: /var/run/secrets/dubbod/ca
            name: dubbo-csr-ca-configmap
            readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: dubbo-ca-root-cert
          optional: true
        name: dubbo-csr-ca-configmap

