apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: dubbo-grpcxds-injector
  labels:
    app: dubbod
    dubbo.apache.org/rev: default
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dubbod
        namespace: dubbo-system
        path: /inject
        port: 443
    failurePolicy: Fail
    name: rev.namespace.grpcxds-injector.dubbo.apache.org
    namespaceSelector:
      matchExpressions:
        - key: dubbo.apache.org/rev
          operator: In
          values:
            - default
        - key: dubbo-injection
          operator: DoesNotExist
    objectSelector:
      matchExpressions:
        - key: grpcxds.dubbo.apache.org/inject
          operator: NotIn
          values:
            - "false"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dubbod
        namespace: dubbo-system
        path: /inject
        port: 443
    failurePolicy: Fail
    name: rev.object.grpcxds-injector.dubbo.apache.org
    namespaceSelector:
      matchExpressions:
        - key: dubbo.apache.org/rev
          operator: DoesNotExist
        - key: dubbo-injection
          operator: DoesNotExist
    objectSelector:
      matchExpressions:
        - key: grpcxds.dubbo.apache.org/inject
          operator: NotIn
          values:
            - "false"
        - key: dubbo.apache.org/rev
          operator: In
          values:
            - default
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dubbod
        namespace: dubbo-system
        path: /inject
        port: 443
    name: namespace.grpcxds-injector.dubbo.apache.org
    namespaceSelector:
      matchExpressions:
        - key: dubbo-injection
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: grpcxds.dubbo.apache.org/inject
          operator: NotIn
          values:
            - "false"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dubbod
        namespace: dubbo-system
        path: /inject
        port: 443
    name: object.grpcxds-injector.dubbo.apache.org
    namespaceSelector:
      matchExpressions:
        - key: dubbo-injection
          operator: DoesNotExist
    objectSelector:
      matchExpressions:
        - key: grpcxds.dubbo.apache.org/inject
          operator: In
          values:
            - "true"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None