---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: dubbo-validator-dubbo-system
  namespace: default
webhooks:
  - name: validation.dubbo.apache.org
    clientConfig:
      service:
        name: dubbod
        namespace: dubbo-system
        path: "/validate"
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - security.istio.io
          - networking.istio.io
        apiVersions:
          - "*"
        resources:
          - "*"
    sideEffects: None
    admissionReviewVersions: ["v1"]

