apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zookeeper
  namespace: {{ .Release.Namespace }}
  labels:
    app: zookeeper
    dubbo.apache.org/rev: {{ default "default" | quote }}
    install.operator.dubbo.apache.org/owning-resource: {{ default "unknown" }}
    operator.dubbo.apache.org/component: "Zookeeper"
    dubbo: zookeeper
    release: {{ .Release.Name }}
    app.kubernetes.io/name: "register"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: zookeeper
      dubbo.apache.org/rev: {{ default "default" | quote }}
      dubbo: zookeeper
