apiVersion: install.dubbo.io/v1alpha1
kind: DubboOperator
metadata:
  namespace: dubbo-system
spec:
  profile: default
  components:
    base:
      enabled: true
    admin:
      enabled: true
  values:
    base:
      global:
        dubboNamespace: dubbo-system



